### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by LonelySqrt** [microsoft/tensorwatch#18]
_thread:Thread = None
           ^
SyntaxError: invalid syntax

**Comment by sytelus** [comment]
That's stange. Are you using Anaconda? If so, could you please copy-paste output of,

```
conda info
```

Also, could you please paste entire error message with call stack?

**Comment by JayYangSS** [comment]
> That's stange. Are you using Anaconda? If so, could you please copy-paste output of,
> 
> ```
> conda info
> ```
> 
> Also, could you please paste entire error message with call stack?

Hi, I'm using Anaconda vitual environment in Jupyter notebook,when I import the package, I get the following error:
```python
Traceback (most recent call last):

  File "f:\anaconda2\envs\python35\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-72273cc44010>", line 1, in <module>
    import tensorwatch as tw

  File "C:\Users\jiyang5\PycharmProjects\tensorwatch-master\tensorwatch\__init__.py", line 6, in <module>
    from .watcher_client import WatcherClient

  File "C:\Users\jiyang5\PycharmProjects\tensorwatch-master\tensorwatch\watcher_client.py", line 5, in <module>
    from .zmq_wrapper import ZmqWrapper

  File "C:\Users\jiyang5\PycharmProjects\tensorwatch-master\tensorwatch\zmq_wrapper.py", line 16
    _thread:Thread = None
           ^
SyntaxError: invalid syntax
```

**Comment by XKMar** [comment]
> > That's stange. Are you using Anaconda? If so, could you please copy-paste output of,
> > ```
> > conda info
> > ```
> > 
> > 
> > Also, could you please paste entire error message with call stack?
> 
> Hi, I'm using Anaconda vitual environment in Jupyter notebook,when I import the package, I get the following error:
> 
> ```python
> Traceback (most recent call last):
> 
>   File "f:\anaconda2\envs\python35\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
> 
>   File "<ipython-input-1-72273cc44010>", line 1, in <module>
>     import tensorwatch as tw
> 
>   File "C:\Users\jiyang5\PycharmProjects\tensorwatch-master\tensorwatch\__init__.py", line 6, in <module>
>     from .watcher_client import WatcherClient
> 
>   File "C:\Users\jiyang5\PycharmProjects\tensorwatch-master\tensorwatch\watcher_client.py", line 5, in <module>
>     from .zmq_wrapper import ZmqWrapper
> 
>   File "C:\Users\jiyang5\PycharmProjects\tensorwatch-master\tensorwatch\zmq_wrapper.py", line 16
>     _thread:Thread = None
>            ^
> SyntaxError: invalid syntax
> ```

try: ~/anaconda3/bin/pip install tensorwatch

**Comment by jimwill3** [comment]
exact same error on my environment. installs w/o any warnings but upon import get: 
 import tensorwatch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorwatch\__init__.py", line 6, in <module>
    from .watcher_client import WatcherClient
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorwatch\watcher_client.py", line 5, in <module>
    from .zmq_wrapper import ZmqWrapper
  File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorwatch\zmq_wrapper.py", line 16
    _thread:Thread = None
           ^
SyntaxError: invalid syntax

**Comment by XKMar** [comment]
> exact same error on my environment. installs w/o any warnings but upon import get:
> import tensorwatch
> Traceback (most recent call last):
> File "", line 1, in 
> File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorwatch__init__.py", line 6, in 
> from .watcher_client import WatcherClient
> File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorwatch\watcher_client.py", line 5, in 
> from .zmq_wrapper import ZmqWrapper
> File "C:\anaconda3\envs\tensorflow\lib\site-packages\tensorwatch\zmq_wrapper.py", line 16
> _thread:Thread = None
> ^
> SyntaxError: invalid syntax

 it maybe caused by your pip environment error, you can try "~/anaconda3/envs/(***your envs name***)/bin/pip install tensorwatch".

**Comment by jimwill3** [comment]
same outcome.

**Comment by mtobeiyf** [comment]
In Tensorwatch source code, I found that there are some syntaxes not supported by Python 3.5.2, including such typing: `_thread:Thread = None` and format string: `print(f"{}")`.
The solution is **switching to Python 3.6+**.
I think the README should point out this, since Ubuntu comes with Python 3.5.2 by default.
