### ISSUE TITLE
AttributeError: module 'torch.onnx' has no attribute 'set_training'

### ISSUE THREAD

**Issue by keosu** [microsoft/tensorwatch#66]
pytorch version: 1.6.0 

```
import sys
import torch
import tensorwatch as tw
import torchvision.models

alexnet_model = torchvision.models.alexnet()
tw.draw_model(alexnet_model, [1, 3, 224, 224])
```

**Comment by btdan** [comment]
I have the same question, Is there anyone solve it?Thanks very much.

**Comment by ckmufeng** [comment]
![image](https://user-images.githubusercontent.com/16316378/92348364-83684280-f105-11ea-8d91-e05c5c04c24f.png)

Maybe we should mofify some code.

**Comment by Nghingtim** [comment]
> I have the same question, Is there anyone solve it?Thanks very much.

Have you solved the problem?

**Comment by kuku-miku** [comment]
Do we have any solution? Thank you,

**Comment by dyh-bupt** [comment]
just change the source code is OK
![image](https://user-images.githubusercontent.com/50792949/96820716-1dd3d980-1459-11eb-86f2-96c319589b2a.png)

**Comment by kuku-miku** [comment]
> just change the source code is OK
> ![image](https://user-images.githubusercontent.com/50792949/96820716-1dd3d980-1459-11eb-86f2-96c319589b2a.png)

so basically you mean to just change "None" to "False"  at line 85 in /home/ant/anaconda3/lib/python3.8/site-packages/tensorwatch/model_graph/hiddenlayerhiddenlayer/summary_graph.py  i.e.


       #with torch.onnx.select_model_mode_for_export(model_clone, None):
        with torch.onnx.select_model_mode_for_export(model_clone, False):

            device = distiller.model_device(model_clone)
            dummy_input = distiller.convert_tensors_recursively_to(dummy_input, device=device)
            self.dummy_input = dummy_input

**Comment by dyh-bupt** [comment]
> > just change the source code is OK
> > ![image](https://user-images.githubusercontent.com/50792949/96820716-1dd3d980-1459-11eb-86f2-96c319589b2a.png)
> 
> so basically you mean to just change at line 85 in /home/ant/anaconda3/lib/python3.8/site-packages/tensorwatch/model_graph/hiddenlayerhiddenlayer/summary_graph.py i.e.
> 
> ```
>     #with torch.onnx.set_training(model_clone, False):
>     #with torch.onnx.select_model_mode_for_export(model_clone, None):
>     with torch.onnx.select_model_mode_for_export(model_clone, False):
> 
>         device = distiller.model_device(model_clone)
>         dummy_input = distiller.convert_tensors_recursively_to(dummy_input, device=device)
>         self.dummy_input = dummy_input
> ```
> 
> well, above changes give another error as below,
> File "/home/ant/anaconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 1083, in _node_getitem
> return getattr(self, sel)(k)
> AttributeError: 'torch._C.Node' object has no attribute 'ival'
> :(
You're right. There are troublesome problems. I've tried PyTorch v0.4, 1.1, 1.6. Now I've given up using tensorwatch. 
Instead, PyTorchViz, tensorboardX and netron are also good tools.

**Comment by wyuzyf** [comment]
Have you solved the problem?

**Comment by Bowenwu1** [comment]
same problem

**Comment by holestine** [comment]
I had this issue due to an old version of TensorBoardX, installing version 2.2 fixed it for me.

**Comment by 102757017** [comment]
Same problem

**Comment by P-HL** [comment]
I try to increase the code from [torch1.13.0,](https://github.com/pytorch/pytorch/blob/master/torch/_C/__init__.pyi.in) which has class Node, but it makes no sense.

**Comment by CheapMeow** [comment]
> I had this issue due to an old version of TensorBoardX, installing version 2.2 fixed it for me.

Seems don't work for me.



> just change the source code is OK ![image](https://user-images.githubusercontent.com/50792949/96820716-1dd3d980-1459-11eb-86f2-96c319589b2a.png)

I meet error:

```
Traceback (most recent call last):
  File "D:\Work\PyCharmProject\nlp-tutorial-master\venv\lib\site-packages\tensorwatch\model_graph\hiddenlayer\pytorch_draw_model.py", line 63, in draw_img_classifier
    g = SummaryGraph(non_para_model, dummy_input)
  File "D:\Work\PyCharmProject\nlp-tutorial-master\venv\lib\site-packages\tensorwatch\model_graph\hiddenlayer\summary_graph.py", line 86, in __init__
    with torch.onnx.select_model_mode_for_export(model_clone, False):
  File "C:\Users\CheapMeow\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "D:\Work\PyCharmProject\nlp-tutorial-master\venv\lib\site-packages\torch\onnx\utils.py", line 88, in select_model_mode_for_export
    raise TypeError(
TypeError: 'mode' should be a torch.onnx.TrainingMode enum, but got '<class 'bool'>'.
```

**Comment by JasonYangCode** [comment]
> Same problem

Same problem
